"""
Slack integration tool for posting messages and summaries.
"""
import requests
import json
from crewai.tools import tool
from config import SLACK_WEBHOOK_URL, BACKEND_URL

@tool("post_slack_message")
def post_slack_message(message: str, channel: str = None, agent_run_id: int = None) -> str:
    """
    Post a message to Slack.

    Args:
        message: Message text (supports markdown)
        channel: Optional channel name (overrides webhook channel)
        agent_run_id: Optional agent run ID for logging

    Returns:
        JSON string with result
    """
    if not SLACK_WEBHOOK_URL:
        return json.dumps({"success": False, "error": "SLACK_WEBHOOK_URL not configured"})

    try:
        # Build the Slack message payload
        payload = {
            "text": message,
            "mrkdwn": True
        }

        if channel:
            payload["channel"] = channel

        # Post to Slack
        response = requests.post(SLACK_WEBHOOK_URL, json=payload, timeout=10)

        success = response.status_code == 200

        # Log the post in the database if agent_run_id is provided
        if success and agent_run_id:
            try:
                log_payload = {
                    "agent_run_id": agent_run_id,
                    "content": message,
                    "success": True
                }
                requests.post(f"{BACKEND_URL}/api/slack/log", json=log_payload, timeout=10)
            except:
                pass  # Logging failed, but message posted successfully

        return json.dumps({
            "success": success,
            "status_code": response.status_code,
            "message": "Message posted to Slack" if success else response.text
        })

    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})

@tool("post_slack_blocks")
def post_slack_blocks(blocks: list, agent_run_id: int = None) -> str:
    """
    Post a formatted Slack message using Block Kit.

    Args:
        blocks: List of Slack Block Kit blocks
        agent_run_id: Optional agent run ID for logging

    Returns:
        JSON string with result
    """
    if not SLACK_WEBHOOK_URL:
        return json.dumps({"success": False, "error": "SLACK_WEBHOOK_URL not configured"})

    try:
        payload = {"blocks": blocks}
        response = requests.post(SLACK_WEBHOOK_URL, json=payload, timeout=10)

        success = response.status_code == 200

        if success and agent_run_id:
            try:
                log_payload = {
                    "agent_run_id": agent_run_id,
                    "content": json.dumps(blocks),
                    "success": True
                }
                requests.post(f"{BACKEND_URL}/api/slack/log", json=log_payload, timeout=10)
            except:
                pass

        return json.dumps({
            "success": success,
            "status_code": response.status_code,
            "message": "Message posted to Slack" if success else response.text
        })

    except Exception as e:
        return json.dumps({"success": False, "error": str(e)})

def build_summary_blocks(summary: str, metrics: dict = None, news_count: int = 0) -> list:
    """
    Build a formatted Slack message with summary and metrics.
    """
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": "📊 Marketing Dashboard Summary"
            }
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"*Agent Analysis Summary*\n{summary}"
            }
        }
    ]

    if metrics:
        metrics_text = "*Key Metrics (Last 7 Days)*\n"
        metrics_text += f"• Spend: ${metrics.get('total_spend', 0):.2f}\n"
        metrics_text += f"• Revenue: ${metrics.get('total_revenue', 0):.2f}\n"
        metrics_text += f"• ROI: {metrics.get('overall_roi', 0):.1f}%\n"
        metrics_text += f"• ROAS: {metrics.get('overall_roas', 0):.2f}x\n"
        metrics_text += f"• Conversions: {metrics.get('total_conversions', 0)}"

        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": metrics_text
            }
        })

    if news_count > 0:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"📰 *News Items Found*: {news_count}"
            }
        })

    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "🤖 Generated by Marketing Dashboard Agent"
            }
        ]
    })

    return blocks
